import Head from "next/head";
import GrowSection from "../components/home/GrowSection";
import HeroSection from "../components/home/HeroSection";
import HomeNavbar from "../components/navbar/HomeNavbar";
import ManegeSection from "../components/home/ManegeSectiom";
import FeedBackSection from "../components/home/FeedBackSecton";
import GiftSection from "../components/home/GiftSection";
import HomeFooter from "../components/footer/HomeFooter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeNavbar />
      <main className={""}>
        <div className="w-full h-px bg-textColor-50"></div>
        <HeroSection />
        <GrowSection />
        <ManegeSection />
        <FeedBackSection />
        <GiftSection />
      </main>

      <footer className="bg-blue-200 text-textColor-white">
        <HomeFooter />
      </footer>
    </div>
  );
}
